// Generated by Wrangler on Mon Sep 16 2024 22:21:51 GMT-0300 (Horário Padrão de Brasília)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	DISCORD_APPLICATION_ID: string;
	DISCORD_PUBLIC_KEY: string;
	DISCORD_TOKEN: string;
	DISCORD_GUILD_ID: string;
	DISCORD_CHANNEL_ID: string;
	GITHUB_WEBHOOK_SECRET: string;
}
